name: Tests
on: [push]

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: 7.3
            extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
            coverage: none
      - name: Run tests
          uses: actions/checkout@v1
          uses: nathanheffley/laravel-phpunit-action@master
